<?php
declare(strict_types=1);

namespace Integration\Console;

use App\HeightBinary\BinaryNode;
use App\HeightBinary\EmptyBinaryNode;
use App\HeightBinary\HeightBinaryCalculator;
use PHPUnit\Framework\TestCase;

class HeightBinaryCommandTest extends TestCase
{
    private HeightBinaryCalculator $calculator;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->calculator = new HeightBinaryCalculator();
    }

    public function testHeightBinaryCommand(): void
    {
        $binary_node = new BinaryNode(1);
        $left_node = new BinaryNode(2);
        $second_left_node = new BinaryNode(2);
        $binary_node->setLeft($left_node);
        $left_node->setLeft($second_left_node);

        $this->assertEquals(3, $this->calculator->calculate($binary_node));
    }

    public function testHeightBinaryCommandWithEmptyNode(): void
    {
        $binary_node = new EmptyBinaryNode();

        $this->assertEquals(0, $this->calculator->calculate($binary_node));
    }

}