<?php
declare(strict_types=1);

namespace Integration\Console;

class LevelOrderTraversalCommandTest extends \PHPUnit\Framework\TestCase
{
    private \App\Console\Commands\LevelOrderTraversalCommand $command;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->command = new \App\Console\Commands\LevelOrderTraversalCommand();
    }

    public function test_print_level_order_traversal(): void
    {
        $node = new \App\SymmetricTree\Models\Node(1);
        $left = new \App\SymmetricTree\Models\Node(2);
        $right = new \App\SymmetricTree\Models\Node(3);
        $printed = $this->command->execute($node);

        $this->assertEquals("Level Order Traversal: 1 2 3 ", $printed);
    }

}